### ISSUE TITLE
Grading job failed- intranet being spotty

### ISSUE THREAD

**Issue by nexusdaniel5306** [illinois-cs241/broadway-on-demand#164]
The illinoisnet network seems to be down right now, and it seemed to cancel my grading job on broadway. Now I have no submissions left for the day, and cannot see feedback

**Comment by nd-0r** [comment]
We can't help you with this on GitHub because this is a public communication channel. Please check EdStem for more information on this.

The issues page for the repo is typically for keeping track of bugs and feature requests to guide open source contribution. Although this is an issue you're having with On-Demand, it's not an issue with the code that a contributor could fix. I hope that explains it better. Sorry we can't help you here.
